<?xml version="1.0"?>
<robot name="sim_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_width"      value="0.30"/>
  <xacro:property name="base_length"     value="0.40"/>
  <xacro:property name="base_height"     value="0.15"/>
  <xacro:property name="wheel_radius"    value="0.05"/>
  <xacro:property name="wheel_width"     value="0.04"/>
  <xacro:property name="wheel_sep"       value="0.34"/>

  <material name="blue">  <color rgba="0.1 0.3 0.8 1.0"/> </material>
  <material name="black"> <color rgba="0.1 0.1 0.1 1.0"/> </material>
  <material name="grey">  <color rgba="0.5 0.5 0.5 1.0"/> </material>
  <material name="red">   <color rgba="0.8 0.1 0.1 1.0"/> </material>

  <!-- BASE -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child  link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.08" iyz="0" izz="0.10"/>
    </inertial>
  </link>

  <!-- WHEEL MACRO -->
  <xacro:macro name="wheel" params="name x_pos y_pos">
    <link name="${name}_wheel">
      <visual>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.002"/>
      </inertial>
    </link>
    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${name}_wheel"/>
      <origin xyz="${x_pos} ${y_pos} 0" rpy="-1.5708 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <xacro:wheel name="left_front"  x_pos=" 0.12" y_pos=" ${wheel_sep/2}"/>
  <xacro:wheel name="right_front" x_pos=" 0.12" y_pos="-${wheel_sep/2}"/>
  <xacro:wheel name="left_rear"   x_pos="-0.12" y_pos=" ${wheel_sep/2}"/>
  <xacro:wheel name="right_rear"  x_pos="-0.12" y_pos="-${wheel_sep/2}"/>

  <!-- CASTER -->
  <link name="caster_link">
    <visual><geometry><sphere radius="0.025"/></geometry><material name="grey"/></visual>
    <collision><geometry><sphere radius="0.025"/></geometry></collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="caster_link"/>
    <origin xyz="-0.17 0 -0.025" rpy="0 0 0"/>
  </joint>

  <!-- LIDAR -->
  <link name="lidar_link">
    <visual><geometry><cylinder radius="0.04" length="0.06"/></geometry><material name="red"/></visual>
    <collision><geometry><cylinder radius="0.04" length="0.06"/></geometry></collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
    </inertial>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="0.15 0 0.10" rpy="0 0 0"/>
  </joint>

  <!-- CAMERA -->
  <link name="camera_link">
    <visual><geometry><box size="0.04 0.08 0.04"/></geometry><material name="grey"/></visual>
    <collision><geometry><box size="0.04 0.08 0.04"/></geometry></collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="camera_link"/>
    <origin xyz="0.19 0 0.08" rpy="0 0 0"/>
  </joint>

  <link name="camera_optical_link"/>
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child  link="camera_optical_link"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
  </joint>

  <!-- GAZEBO PLUGINS -->
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <left_joint>left_front_wheel_joint</left_joint>
      <right_joint>right_front_wheel_joint</right_joint>
      <left_joint>left_rear_wheel_joint</left_joint>
      <right_joint>right_rear_wheel_joint</right_joint>
      <wheel_separation>${wheel_sep}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>false</publish_wheel_tf>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>

  <gazebo reference="lidar_link">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range><min>0.12</min><max>10.0</max><resolution>0.01</resolution></range>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros><remapping>~/out:=scan</remapping></ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <camera>
        <horizontal_fov>1.0856</horizontal_fov>
        <image><width>640</width><height>480</height><format>R8G8B8</format></image>
        <clip><near>0.05</near><far>100</far></clip>
      </camera>
      <plugin name="camera_driver" filename="libgazebo_ros_camera.so">
        <ros>
          <remapping>image_raw:=camera/image_raw</remapping>
          <remapping>camera_info:=camera/camera_info</remapping>
        </ros>
        <camera_name>camera</camera_name>
        <frame_name>camera_optical_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>
